### ISSUE TITLE
when-inside

### ISSUE THREAD

**Issue by jonscottclark** [HugoGiraudel/sass-boilerplate#10]
Hey Hugo, nice boilerplate, learned some things from it — thanks for sharing!

I just had a question about your `when-inside` mixin. What's the use case for this? What makes it preferable to just writing `#context & { ... }`?

https://github.com/HugoGiraudel/sass-boilerplate/blob/master/stylesheets/utils/_mixins.scss#L29-L33

**Comment by HugoGiraudel** [comment]
`#context & { .. }` might be confusing for beginners. `@include when-inside('#context') { .. }` is more descriptive. :)

**Comment by jonscottclark** [comment]
Thanks for the reply :)
