### ISSUE TITLE
Responsive common utils?

### ISSUE THREAD

**Issue by Kcko** [HugoGiraudel/sass-boilerplate#11]
Where should i place common simple responsive rules? 
My opinion is 3.   'base/responsive';

**Comment by HugoGiraudel** [comment]
Why do you mean by *responsive rules*?

**Comment by Kcko** [comment]
I like to have common set of responsive rules 

/* Very common responsive rules
---------------------------------------------------------------------------------------------------- */
 
img 
{
	max-width: 100%;
	height: auto;
}


@media \0screen 
{
	img 
	{ 
		width: auto; /*  ie 8 */
	}
}


etc.

This file i missing in your awesome skelet.

**Comment by HugoGiraudel** [comment]
Oh. I guess I would put it in `base/base`.

**Comment by Kcko** [comment]
My opinion is separate file in /base ... ; but thx :)

**Comment by Kcko** [comment]
Hugo, I have one = last question.

Whats different between _base.scss and _typography.scss.

I think that are equals.

Styles for body, H1-H6, commons para etc can be inserted in both.

Can you show me some god example (that i understand distinction).

Thx very much

S pozdravem

Roman Janko
Frontend Specialist / PHP Developer

			

gsm: [+420] 777 856 657
email: admin@rjwebdesign.cz <mailto:admin@rjwebdesign.cz>
icq: 176-031-471
www: rjwebdesign.cz <http://rjwebdesign.cz>
linkedin: linkedin.com/in/romanjanko 
<http://www.linkedin.com/in/romanjanko>
twitter: twitter.com/RomanJanko <https://twitter.com/RomanJanko>

			

Rjwebdesign logo

Dne 2.12.2015 v 11:18 Hugo Giraudel napsal(a):

**Comment by HugoGiraudel** [comment]
In `_typography.scss`, you will stuff everything related to your typography: font styles for headings, content elements, your modular scale, etc.

In `_base.scss`, you could have some browser resets, the box-sizing reset, and various rules targeting default elements that are not related to typography.

**Comment by Kcko** [comment]
+1 :-)

S pozdravem

Roman Janko
Frontend Specialist / PHP Developer

			

gsm: [+420] 777 856 657
email: admin@rjwebdesign.cz <mailto:admin@rjwebdesign.cz>
icq: 176-031-471
www: rjwebdesign.cz <http://rjwebdesign.cz>
linkedin: linkedin.com/in/romanjanko 
<http://www.linkedin.com/in/romanjanko>
twitter: twitter.com/RomanJanko <https://twitter.com/RomanJanko>

			

Rjwebdesign logo

Dne 2.12.2015 v 14:42 Hugo Giraudel napsal(a):
