### ISSUE TITLE
Tests folder

### ISSUE THREAD

**Issue by robsonsobral** [HugoGiraudel/sass-boilerplate#14]
Hi, @HugoGiraudel.

Have you ever thought about a folder for tests?

**Comment by HugoGiraudel** [comment]
Hey.

Very, very, very few people actually test their CSS like it is commonly done with other programming languages. In case there are a lot of tests, it makes a lot of sense to have a test folder, definitely.

**Comment by robsonsobral** [comment]
I agree. I think it follows in the same case of `themes` folder: a very specific case. The themes folder is my reason to suggest it.

**Comment by HugoGiraudel** [comment]
Definitely.

**Comment by HugoGiraudel** [comment]
Moved to https://github.com/HugoGiraudel/sass-guidelines/issues/367.
