### ISSUE TITLE
functions and variables order

### ISSUE THREAD

**Issue by robsonsobral** [HugoGiraudel/sass-boilerplate#15]
Hi!

I'm putting my mess in order using this boilerplate and found a issue.

Shouldn't the `functions` file came before the `variables` one? We can use functions to modify variables and functions don't run until being called somewhere.

Example:

```sass
$_color-base-grey: rgb(229, 231, 234);

$_palettes: (
	'purple': (
		'base': rgb(42, 40, 80),
		'light': rgb(51, 46, 140),
		'dark': rgb(40, 38, 65)
	),
	'grey':  (
		'base': $_color-base-grey,
		'light': tint($_color-base-grey, 10%),
		'dark': shade($_color-base-grey, 10%)
	)
);
```

Thank for your help!

**Comment by HugoGiraudel** [comment]
> Shouldn't the functions file came before the variables one?

It should have literally no impact.

> We can use functions to modify variables and functions don't run until being called somewhere.

See https://github.com/HugoGiraudel/sass-boilerplate/issues/16#issuecomment-242905687.

**Comment by robsonsobral** [comment]
Is this color use case so anti pattern? Please, what do you suggest for this situation?

**Comment by HugoGiraudel** [comment]
What are you trying to do?

**Comment by robsonsobral** [comment]
Exactly what is the code:

```sass
[...]
        'light': tint($_color-base-grey, 10%),
        'dark': shade($_color-base-grey, 10%)
[...]
```

In the case of a number, I can sum to a previous variable. Let's say:

```sass
$a: 10;
$b: $a+2;
```

This isn't the case with colors. I need a function to modify them.

**Comment by HugoGiraudel** [comment]
Gotcha. Well, you could rely on the native one rather than a custom one?

**Comment by robsonsobral** [comment]
Welll... It looks like Sass could have native `tint` and `shade` functions... But you gonna disagree (again).

To have them on `functions.scss` happens to be useless, if I gonna keep this organization.

Thank you really much! You are always helpful. I'm sorry for bother you! Thanks.

**Comment by HugoGiraudel** [comment]
> Welll... It looks like Sass could have native tint and shade functions... But you gonna disagree (again).

`tint(..)` and `shade(..)` are just aliases for `mix(..)` with white and black. It’s easy to use `mix(..)` instead.

> To have them on functions.scss happens to be useless, if I gonna keep this organization.

You can totally put `_functions.scss` first. :)
