### ISSUE TITLE
Exclude vendor folder from lint

### ISSUE THREAD

**Issue by robsonsobral** [HugoGiraudel/sass-boilerplate#17]
I'll not pull request it, because I can't find the reason it isn't working on my test.

The `.scss-lint.yml` should have this [on its first line](https://github.com/brigade/scss-lint#configuration):

``` yaml
exclude: 'stylesheets/vendor/*.*'
```

I'm testing on Sublime Text, but no luck yet... I gonna try more.

**Comment by HugoGiraudel** [comment]
What do you mean “testing on Sublime Text”?

**Comment by robsonsobral** [comment]
Sublime Linter. It keeps linting the file, even with the `exclude`.

**Comment by HugoGiraudel** [comment]
I think it might be something to do with it then. I’m sorry I don’t use in-IDE linters.

**Comment by robsonsobral** [comment]
I don't even know how to "not use" them. That is the reason I didn't test it yet.

**Comment by HugoGiraudel** [comment]
I think it’s worth a PR. Do you mind? :)
