### ISSUE TITLE
Nesting depth warning on BEM structure

### ISSUE THREAD

**Issue by marcoturi** [HugoGiraudel/sass-boilerplate#18]
The above code will throw a warning (nesting should not be greater than 1) from sass lint:

```
.example {
  top: 43px;
  &__section { // <-- this line
    width: 100%;
  }
}
```

**Comment by HugoGiraudel** [comment]
Yep. It's expected. :)

**Comment by marcoturi** [comment]
But it's not a nesting selector. What should we do in project using BEM ? Disable the sass lint rule ? Or use a mixin instead of & ? Thank you for your fast response :)

**Comment by HugoGiraudel** [comment]
It definitely is a nested selector. It might not generate a compound selector but it still generates a selector nevertheless. I’d recommend you don’t use selector nesting entirely, but that’s really up to you.

**Comment by marcoturi** [comment]
if I avoid the the syntax of the first post, following your advice to "....have the base name repeated. " (from [here](https://www.sitepoint.com/beware-selector-nesting-sass/) . For example:
```
.example {
 top: 43px;
}

.home__section { //<-- this line again
  width: 100%;
}
```
I get another warning from sass-lint about the regexp for the "__"

**Comment by HugoGiraudel** [comment]
Okay, that might be a bug then. :)
Are you using the configuration from this repo?

**Comment by HugoGiraudel** [comment]
Just updated the configuration for `SelectorFormat`, care to try it?

**Comment by marcoturi** [comment]
No warnings now. Thank you!

**Comment by HugoGiraudel** [comment]
Lovely. :)
