### ISSUE TITLE
index.scss (eyeglass-style)

### ISSUE THREAD

**Issue by strarsis** [HugoGiraudel/sass-boilerplate#21]
Would it make sense using 'index.scss' according to [sass-eyeglass module spec](https://github.com/sass-eyeglass/eyeglass#writing-an-eyeglass-module-with-sass-files) 
as main/"entry" file for the project instead main.scss?

**Comment by HugoGiraudel** [comment]
Hello. That would go against Sass Guidelines, however we could certainly add a comment in there to recommend people to rename it if they are heavily using on Eyeglass for distribution. :)

**Comment by HugoGiraudel** [comment]
Done: https://github.com/HugoGiraudel/sass-boilerplate/commit/9dd94186449a803788ab1ebe067b023d48f62c62. Thank you!

**Comment by robsonsobral** [comment]
I worked in a project which I had to create another main file: `_layouts/main`. Since you have `main` HMTL element and `role=main`, to rename the point of entry file as `index` sounds like a good idea.
