### ISSUE TITLE
Rename themes to...

### ISSUE THREAD

**Issue by robsonsobral** [HugoGiraudel/sass-boilerplate#22]
I know I already suggested a change on the name of this folder and, exactly because of that, why not name it `others`?

;-)

**Comment by HugoGiraudel** [comment]
Because `others` is a dumpster and does not encourage any good practice and proper tidy behaviour regarding file organisation. It’s what you use when you don’t know where to put it, and that’s usually a recipe for disaster in a team on the long run.

**Comment by robsonsobral** [comment]
Good point. Files I already struggled to find a place:

- `_shame.scss`
- `_print.scss`

**Comment by HugoGiraudel** [comment]
I’d put them in `base/`.

**Comment by robsonsobral** [comment]
It's fine for `_print.scss`, but not for `_shame.scss`, since they're supposed to be the last style of all (where you put that nasty workarounds you don't have time to give much though).

---

OFF-TOPIC: you and Miriam Suzanne should be awarded with a prize for the most patience people on github).

**Comment by HugoGiraudel** [comment]
> It's fine for `_print.scss`, but not for `_shame.scss`, since they're supposed to be the last style of all (where you put that nasty workarounds you don't have time to give much though).

Feel free to include `_shame.scss` at the very end of the main file if necessary. :)

Ping @mirisuzanne for the kind words. :)

**Comment by robsonsobral** [comment]
Thank you!
