### ISSUE TITLE
Importing in main.scss fails using gulp-sass

### ISSUE THREAD

**Issue by selrond** [HugoGiraudel/sass-boilerplate#23]
This is what it (Gulp) throws
```
Error in plugin 'sass'
Message:
    src\sass\main.scss
Error: File to import not found or unreadable: abstracts/variables.
       Parent style sheet: C:/Users/Selrond/Desktop/Code/100DaysOfCode/003/src/sass/main.scss
        on line 4 of src/sass/main.scss
>> @import
   ^
```

It looks as if [the second way of importing the partials](https://sass-guidelin.es/#main-file) fails to compile on gulp-sass?

**Comment by HugoGiraudel** [comment]
Interesting. Are you using https://github.com/dlmanning/gulp-sass?

**Comment by selrond** [comment]
@HugoGiraudel Yes I do use the one you mentioned. Is this a valid SASS syntax you use in your main.scss? What do you use to compile SASS?

**Comment by HugoGiraudel** [comment]
It is documented in Sass official documentation: http://sass-lang.com/documentation/file.SASS_REFERENCE.html#import. I recommend you open an issue on gulp-sass repository then. :)

**Comment by selrond** [comment]
@HugoGiraudel I did, thanks for the link and suggestion.

**Comment by HugoGiraudel** [comment]
Feel free to keep me updated. :)

**Comment by selrond** [comment]
@HugoGiraudel Here or some other communication channel?

**Comment by HugoGiraudel** [comment]
Here is fine.
