### ISSUE TITLE
Clarify the License

### ISSUE THREAD

**Issue by pksadiq** [HugoGiraudel/sass-boilerplate#27]
I hope that the code is public domain. It would be nice if this is explicitly stated in README.

**Comment by HugoGiraudel** [comment]
Fixed with https://github.com/HugoGiraudel/sass-boilerplate/commit/a11ae8e0e8930dfba690a62ac6cd8ffd2b64e01a. Sorry about this.

**Comment by pksadiq** [comment]
heh, sorry to say that I was excepting a public domain license. But it's your code. You have your choice.

So is it okay to use https://sass-guidelin.es/#architecture details as public domain? I'm creating a simple theme that shall be into public domain (CC0), so I can't use non public domain resources

**Comment by HugoGiraudel** [comment]
Regarding your link, this is not directly linked to this repository. This is part of [Sass Guidelines](https://github.com/HugoGiraudel/sass-guidelines#license) which states: 

> The code for this project is licensed under MIT. The content for this project is licensed by Creative Commons Attribution 4.0 International.

Given this repository is related to Sass Guidelines, it makes sense both share the same license when it comes to code. 

Most of my code is licensed under MIT, which is a common and permissive license for open-source. Isn’t it enough for what you are trying to achieve?

**Comment by pksadiq** [comment]
> Most of my code is licensed under MIT, which is a common and permissive license for open-source. Isn’t it enough for what you are trying to achieve?

Probably. I'll just keep the directory structure and write my own code to be safe.

Thanks
