### ISSUE TITLE
Rewrite the recommendation for vendor (Proposal)

### ISSUE THREAD

**Issue by webmarkelov** [HugoGiraudel/sass-boilerplate#28]
Hi, @HugoGiraudel! Thanks for awesome the boilerplate.

When I use webpack I importing any vendor library like as:

```scss
// 2. Vendors
@import
'~normalize.css',
'~bootstrap/scss/bootstrap-grid.scss';
```
Maybe Do you need rewrite recommendation how work with vendor libraries when using webpack or similar tool?

**Comment by HugoGiraudel** [comment]
That’s not a bad idea, however that sounds rather pipeline specific and am not sure is worth putting in Sass Guidelines. I’ll think about it.
