### ISSUE TITLE
Question about multi-page use.

### ISSUE THREAD

**Issue by JohnPevien** [HugoGiraudel/sass-boilerplate#36]
Hi!

From what I understand all of the sass is compiled into a single CSS.
What would be a good approach if I use it with asp MVC app, where I bundle the CSS files that are only used for that specific view, should I have more files aside from "_main.scss_" ?

**Comment by HugoGiraudel** [comment]
Hello John,

I assume you would have different entry points instead of only `main.scss`, yes. :)

**Comment by JohnPevien** [comment]
Thanks! 👍
