### ISSUE TITLE
Shouldn't macro components (layout) be imported AFTER micro components (modules)?

### ISSUE THREAD

**Issue by AradAral** [HugoGiraudel/sass-boilerplate#38]
Hi there! I'm struggling to understand something, please let me know if I'm missing some point. Thank you!

Naturally, many of our macro components (which are located in the "layout" folder) are composed of (i.e. contain) some micro components (modules).

For example, a header (macro) has a search box that is actually a textbox module (micro). Pretty straight-forward so far.

I'm also following the BEM methodology, so this relationship would look something like this;
- We have a block named `.textbox` (=> `components/_textbox.scss`)
- Then in our header block (=> `layout/_header.scss`), we have an element (and by element I mean a BEM element) named `.header__search-box`. As you know this is called a "mix" in BEM, and is perfectly valid and common.

Now, the `header-search-box` element might need to override some of the default declarations on the `.textbox` block.

This means that `layout/_header.scss` has to be imported after `components/_textbox.scss` in order for its declarations to take precedence, obviously. But I noticed that the [7-1 architecture](https://sass-guidelin.es/#the-7-1-pattern) states the following:

> Files should be imported according to the folder they live in, one after the other in the following order:
> 
> abstracts/
> vendors/
> base/
> layout/
> components/
> pages/
> themes/

Components should be imported AFTER layouts. This doesn't make a lot of sense to me. And it would actually be problematic in cases like the one I just described. I wanted to know what the specific rationale behind this particular order is, and whether you think the case I'm presenting is reasonable or not.

What I'm saying in a nutshell is: Macro components are composed of micro components. In many cases, micro components would need to change style depending on the context they're used (meaning within which macro component), this is achieved in BEM with mixes, but it would only work if macro component styles are located AFTER the micro component styles in the final stylesheet. But the 7-1 architecture recommended order of importing files doesn't allow this.

Thanks in advance.

**Comment by HugoGiraudel** [comment]
Hello!

> Components should be imported AFTER layouts. This doesn't make a lot of sense to me. But this would be problematic in cases like the one I just described. I wanted to know what the specific rationale behind this particular order is, and whether you think the case I'm presenting is reasonable or not.

I think it does make some sense to me. Layouts are more macro than components, so components should be imported *after* so their styles take precedence, would they be conflicting. For instance, the header might impose a blue text color, but a specific component within the header needs to be white.

> What I'm saying in a nutshell is: Macro components are composed of micro components. In many cases, micro components would need to change style depending on the context they're used (meaning within which macro component), this is achieved in BEM with mixes, but it would only work if macro component styles are located AFTER the micro component styles in the final stylesheet. But the 7-1 architecture recommended order of importing files doesn't allow this.

Remember that Sass Guidelines are just that: guidelines. If they feel odd to you, you should feel free to adjust your take on them. As you say, composition can be achieved with proper BEM, but if style precedence is more natural or better suited for your project, it’s totally fine to change the order of imports. :)

**Comment by AradAral** [comment]
@HugoGiraudel Okay, got it. Thanks Hugo!
