### ISSUE TITLE
Component before Layout when compiling?

### ISSUE THREAD

**Issue by brianmontanaweb** [HugoGiraudel/sass-boilerplate#4]
Even though your documentation says macro first wouldn't it help with defining the micro and building up from that?

**Comment by HugoGiraudel** [comment]
It should not matter much since components and layouts are not supposed to styles the same things anyway.

**Comment by macmladen** [comment]
It does not matter, however I see that order in `main.scss` have layout before component now so this may be closed now.

**Comment by HugoGiraudel** [comment]
Fair enough!
