### ISSUE TITLE
main.scss only includes base.scss, not the others

### ISSUE THREAD

**Issue by macmladen** [HugoGiraudel/sass-boilerplate#6]
There are `fonts`, `helpers` and `typography` in `base`folder and those three are not included in `main`or anywhere in boilerplate.

If it is intentional then it should be noted in **README.md**.

Or is it just an oversight?

**Comment by HugoGiraudel** [comment]
It is an error. Do you feel like providing a PR? :)

**Comment by macmladen** [comment]
In a minute.

**Comment by macmladen** [comment]
Merged, could be closed.
