### ISSUE TITLE
Maybe abstracts instead of utils?

### ISSUE THREAD

**Issue by macmladen** [HugoGiraudel/sass-boilerplate#7]
I saw this in **Omega 4.x** theme for Drupal and adopted myself as those are abstracts — not generating anything on their own.

**Comment by HugoGiraudel** [comment]
Could be worth adding a note about this I guess.

**Comment by macmladen** [comment]
I was actually proposing to change `utils` to `abstracts` in order to better reflect its nature that it does not generate any code (or output) as all things that it contains are just **abstracts** (being variables, functions and mixins).

I would also suggest adding `_init.scss` that would be first and hold initialization of some variables needed by used frameworks like [Zen Grids](https://github.com/JohnAlbin/zen-grids) or [Susy](https://github.com/ericam/susy).

I also think that those abstracts should be loaded **before** `_normalize.scss` (that could be borrowed from [@JohnAlbin](https://github.com/npmcomponent/JohnAlbin-normalize-scss) which is truly **sass** and more, based on included [@necolas normalize.css](https://github.com/necolas/normalize.css)) so that order should be:

1. **abstracts** _(initialization - no code, probably should include codeless frameworks like zen or susy)_
2. **vendors** _(reset and frameworks that produce some code)_
3. **base** _(element styling and common site-wide stuff)_
4. **layout** _(where all layout lives)_
5. **components** _(movable widgets)_
6. **page** _(page specifics)_
7. **theme** _(reskining where needed)_

**Comment by HugoGiraudel** [comment]
I'll rethink this. Care opening this issue with your comment on Sass-Guidelines repo?

**Comment by macmladen** [comment]
Split and moved to sass-guidelines, could be closed.
