### ISSUE TITLE
Change normalize.css to John Albin _normalize.scss

### ISSUE THREAD

**Issue by macmladen** [HugoGiraudel/sass-boilerplate#9]
The current version is actually just inlcuded `normalize.css`.

[@JohnAlbin](https://github.com/npmcomponent/JohnAlbin-normalize-scss) is truly **sass**, offer some control on final output and is based on currently included [@necolas normalize.css](https://github.com/necolas/normalize.css)

**Comment by HugoGiraudel** [comment]
I’d argue that’s not necessarily a good idea. I like having the original version from Nicolas Gallagher to be honest.
